stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - params.yaml
      - ai4i2020.csv
    outs:
      - data/processed

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - params.yaml
      - data/processed/cleaned_data.csv

    outs:
      - data/preprocessed/X_train.csv
      - data/preprocessed/X_test.csv
      - data/preprocessed/y_train.csv
      - data/preprocessed/y_test.csv

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/preprocessed/X_train.csv
      - data/preprocessed/y_train.csv

    outs:
      - model/Xgboost_model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - data/preprocessed/X_test.csv
      - data/preprocessed/y_test.csv
      - model/Xgboost_model.pkl
    outs:
      - evaluation/evaluation_report.json

